# Generated by Django 5.2.8 on 2025-12-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='download_link',
        ),
        migrations.AlterField(
            model_name='app',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
