# Generated by Django 5.2.8 on 2025-12-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_app_download_link_alter_app_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='apk_file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
    ]
