# Generated by Django 5.2.8 on 2025-12-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_app_apk_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_main_app',
            field=models.BooleanField(default=False),
        ),
    ]
