# Generated by Django 5.2.8 on 2025-12-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_app_is_main_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='downloads/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
