# Generated by Django 5.2.8 on 2025-12-15 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mainapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='is_main_app',
        ),
        migrations.RemoveField(
            model_name='mainapp',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mainapp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainapp',
            name='description',
            field=models.TextField(default='تحديث التطبيق الرئيسي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainapp',
            name='title',
            field=models.CharField(default='MyServicesPro', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainapp',
            name='apk_file',
            field=models.FileField(default='MyServicesPro', upload_to='downloads/'),
            preserve_default=False,
        ),
    ]
