# Generated by Django 5.2.8 on 2026-01-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_app_is_active_app_is_main_app_downloadhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadHistory',
        ),
    ]
