# Generated by Django 5.2.8 on 2026-01-08 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadhistory',
            name='main_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mainapp'),
        ),
        migrations.AlterField(
            model_name='downloadhistory',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.app'),
        ),
    ]
